repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        files: ^[src/|test]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [ python ]
        files: ^[src/|test]
      - id: pytest-check
        name: pytest-check
        entry: pytest .
        language: system